apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: platform
  name: vault
  labels:
    name: key-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashicorp-vault
  template:
    metadata:
      labels:
        app: hashicorp-vault
    spec:
      containers:
      - name: hashicorp-vault
        image: hashicorp/vault
        ports:
        - containerPort: 80
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsGroup: 1000
          runAsNonRoot: true
          drop:
            - ALL
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
