apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: platform
  name: vault
  labels:
    name: key-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashicorp-vault
  template:
    metadata:
      labels:
        app: hashicorp-vault
    spec:
      containers:
      - name: hashicorp-vault
        image: hashicorp/vault
        ports:
        - containerPort: 80
        securityContext:
          allowPriviliegeEscalation: false
          runAsGroup: 1000
          runAsNonRoot: true
