name: main:branch

# Controls when the workflow will run
on: [pull_request]
  
jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: kubescape/github-action@main
      continue-on-error: false
      with:  
        frameworks: NSA, MITRE
        verbose: true
        severityThreshold: low
    
